CREATE EXTENSION IF NOT EXISTS vector;
ALTER TABLE knowledge_documents ADD COLUMN embedding vector(768);

INSERT INTO knowledge_documents (title, category, content) VALUES
('Getting Started','Product Guide',$$To get started with LearnLoop: 1) Sign in as the account admin using the invitation email. 2) Complete the setup checklist under Home > Setup. 3) Create your first course. 4) Invite instructors and learners. 5) Publish the course. Most customers finish setup within one week. Contact your Customer Success Manager for onboarding sessions.$$),
('User Management','Product Guide',$$Admins can add instructors under Settings > Users > Invite User. Enter the email, choose the role Instructor, and select Send Invite. Invitations expire after 7 days and can be resent. Roles: Admin, Instructor, Learner. Only Admins can change roles or deactivate users. Bulk import is available through Settings > Users > Import CSV (max 500 rows).$$),
('Course Management','Product Guide',$$Create a course from Courses > New Course. Add modules, lessons, and quizzes. Courses stay in Draft until published. Assign an instructor under Course Settings > Instructors. Learners can be enrolled individually, by group, or by self-enrollment link. Archived courses keep their reports but are hidden from learners.$$),
('Reporting','Product Guide',$$Reports are under Analytics: Course Completion, Learner Activity, Quiz Results, and Instructor Engagement. Filter by date, course, or group. Export to CSV or PDF with the Export button (CSV exports are limited to 50,000 rows). Admins on Professional and Enterprise plans can schedule weekly or monthly report emails.$$),
('Integrations','Product Guide',$$LearnLoop integrates with Google Workspace, Microsoft Teams, Zoom, and Slack. Enterprise plans also support SAML SSO and a REST API. Configure integrations under Settings > Integrations. SSO setup requires an Admin and your identity provider metadata file. API keys are created under Settings > API and must never be shared.$$),
('Common Issues','Product Guide',$$Common issues: 1) CSV export fails: reduce the date range or keep rows under 50,000, then retry. 2) Invitation email not received: check spam, then resend from Settings > Users. 3) Learner cannot see a course: confirm it is published and the learner is enrolled. 4) Bulk import errors: match the CSV template and keep it to 500 rows. If the issue continues, contact support with a screenshot and the time of the error.$$),
('Adoption Blockers','Playbook',$$Adoption blockers: stalled setup, low login rates, no published courses, missing admin sponsor, unclear internal ownership, integration problems. Steps: confirm the blocker with the customer, document it in the customer record, offer an enablement session within 5 business days, and create a follow-up task for the account owner. Escalate to the CS Manager if adoption score stays below 40 after 30 days.$$),
('At-Risk Customers','Playbook',$$A customer is at risk when adoption score is below 40, sentiment is repeatedly negative, there are multiple unresolved issues, or renewal is within 90 days with open concerns. Actions: notify the account owner, create a risk review task, and schedule a call within 3 business days. Never promise discounts, credits, or contract changes without manager approval.$$),
('Escalation Rules','Playbook',$$Escalate to the CS Manager when: a customer has 3 or more unresolved interactions, the customer threatens to cancel, an issue affects many learners, or there is a security or data concern. Severity: High for cancellation threats or repeated failures, Critical for security or data loss. Escalated cases require human review before any customer reply.$$),
('Billing Questions','Playbook',$$Billing and administrative questions (invoices, payments, refunds, pricing, contract changes) are handled by the Billing Team, not by Customer Success automation. Do not confirm refunds, credits, or price changes. Acknowledge the request, tell the customer the Billing Team will respond within 2 business days, and route the case to billing@learnloop.example.$$),
('Renewal Guidance','Playbook',$$Start renewal conversations 90 days before the renewal date. Review adoption score, open issues, and usage trends first. Customers with an adoption score below 50 need a success plan before renewal discussions. Pricing and contract terms are handled by the account owner and Sales, never by automated responses.$$),
('Account Questions','FAQ',$$How do I reset my password? Use Forgot Password on the sign-in page; the reset link is valid for 60 minutes. How do I change the account owner email? Contact support from the current admin email. How do I deactivate a user? Admins can do this in Settings > Users. Deactivated users keep their historical data.$$),
('Feature Questions','FAQ',$$Does LearnLoop support certificates? Yes, completion certificates can be enabled per course. Does it support live classes? Zoom and Teams integrations launch live sessions from a course. Is there a mobile app? Learners can use the mobile web experience; a native app is not available. Feature ideas are collected by Customer Success and reviewed monthly by Product.$$),
('Configuration','FAQ',$$How do I set the organization logo and colors? Settings > Branding. How do I set the default language? Settings > General > Language. How do I enable self-enrollment? Course Settings > Enrollment > Enable link. Time zone and email notification settings are under Settings > General.$$),
('Best Practices','FAQ',$$Best practices: assign at least two admins, publish one course in the first two weeks, group learners by team, schedule weekly completion reports, and review Learner Activity monthly. Customers who invite instructors within the first 14 days adopt faster.$$);